REPO_TAGLINE: Statistical mechanics • ensembles • phase transitions
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: library
SITE_URL: https://academic-codex.github.io/PGF5006-Mecanica-Estatistica

BG_1: "#022C22"
BG_2: "#064E3B"
TEXT_MAIN: "#ECFDF5"
TEXT_MUTED: "#99F6E4"
ACCENT: "#2DD4BF"
CARD_RADIUS: "18"